//using NetOffice.DAOApi;
//using NetOffice.DAOApi.Enums;

using Easislides.Util;
using System;
using System.ComponentModel;
using System.Data;
//using System.Data.SQLite;
using System.Drawing;
using System.IO;
using System.Text;
using System.Windows.Forms;

using Easislides.SQLite;
using Easislides.Module;
#if SQLite
using DbConnection = System.Data.SQLite.SQLiteConnection;
#elif MariaDB
using DbConnection = MySql.Data.MySqlClient.MySqlConnection;
using DbDataAdapter = MySql.Data.MySqlClient.MySqlDataAdapter;
using DbCommandBuilder = MySql.Data.MySqlClient.MySqlCommandBuilder;
using DbCommand = MySql.Data.MySqlClient.MySqlCommand;
using DbDataReader = MySql.Data.MySqlClient.MySqlDataReader;
using DbTransaction = MySql.Data.MySqlClient.MySqlTransaction;
#endif

namespace Easislides
{
    public partial class FrmGenerateHtml : Form
	{
		private const string EasiSlidesInfo = "Auto-Generated by EasiSlides";

		private int[] SongFolderLog = new int[1];

		private int[,] FolderFNum = new int[Gf.MAXSONGSFOLDERS, 1];

		private int CurrentSong;

		private int CurSlide;

		private bool ChorusDone;

		private bool ShowFirstLineOnly;

		private string CopyrightInfo;

		private string UserRefInfo;

		private string BookRefInfo;

		private string WriterInfo;

		private string SongTitle2;

		private string SongTitle;

		private int SongCapo;

		private string SongKey;

		private int SongFolderNo;

		private string SongNotations;

		private string SongLyrics;

		private string SongSequence;

		private bool NotationsPresent = false;

		private bool ShowNotations = true;

		private int CurFormat;

		private int[] HTML_ShowHeadings = new int[4];

		private string NewLine;

		private SongSettings HtmlItem = new SongSettings();

		private string EasiSlidesInfoComments = "<!-- Auto-Generated by EasiSlides";

		private string EasiSlidesInfoCommentsEnd = " -->\r\n";

		private string MainHeaderInfo1 = "{\\rtf1\\ansi\\ansicpg1252\\deff0\\deflang1033{\\fonttbl{\\f0\\fnil\\fcharset0 Microsoft Sans Serif;}}\\viewkind1\\uc1\\pard\\f0\\fs24\\margr800\\margl1200\\margt800\\margb800 ";

		private ListView SubDivideList = new ListView();

		private int RTFMaxTextWidth;

		public FrmGenerateHtml()
		{
			InitializeComponent();
		}

		private void FrmGenerateHTML_Load(object sender, EventArgs e)
		{
			Text = "Generate HTML files for " + Gf.CurPraiseBook;
			HeadingText0.Text = RegUtil.GetRegValue("config", "HTML_Publisher", "");
			HeadingText1.Text = RegUtil.GetRegValue("config", "HTML_Web", "");
			HeadingText2.Text = RegUtil.GetRegValue("config", "HTML_Info1", "");
			Gf.HTMLShowNumbers = ((RegUtil.GetRegValue("config", "HTML_ShowNumbers", 0) == 1) ? true : false);
			Gf.HTMLShowChorusItalics = ((RegUtil.GetRegValue("config", "HTML_ShowChorusItalics", 1) == 1) ? true : false);
			Gf.HTMLMusicLink = ((RegUtil.GetRegValue("config", "HTML_Musiclink", 1) == 1) ? true : false);
			Gf.HTMLShowIndex = ((RegUtil.GetRegValue("config", "HTML_ShowIndex", 1) == 1) ? true : false);
			Gf.HTMLShowBookRef = ((RegUtil.GetRegValue("config", "HTML_ShowBookReference", 1) == 1) ? true : false);
			Gf.HTMLShowUserRef = ((RegUtil.GetRegValue("config", "HTML_ShowUserReference", 1) == 1) ? true : false);
			Gf.HTMLDoubleByte = ((RegUtil.GetRegValue("config", "HTML_DoubleByte", 0) == 1) ? true : false);
			Gf.HTMLDocumentOption = RegUtil.GetRegValue("config", "HTML_DocumentOption", 0);
			Gf.HTMLDocumentOption = ((Gf.HTMLDocumentOption >= 0 && Gf.HTMLDocumentOption <= 1) ? Gf.HTMLDocumentOption : 0);
			Gf.HTMLRTFFontSize = RegUtil.GetRegValue("config", "HTML_RTFFontSize", 12);
			Gf.HTMLRTFFontSize = ((Gf.HTMLRTFFontSize < 6 || Gf.HTMLRTFFontSize > 99) ? 12 : Gf.HTMLRTFFontSize);
			MusicLinkcb.Checked = Gf.HTMLMusicLink;
			ShowindexFilecb.Checked = Gf.HTMLShowIndex;
			MusicNumberscb.Checked = Gf.HTMLShowNumbers;
			ChorusItaliccb.Checked = Gf.HTMLShowChorusItalics;
			BookRefcb.Checked = Gf.HTMLShowBookRef;
			UserRefcb.Checked = Gf.HTMLShowUserRef;
			DoubleBytecb.Checked = Gf.HTMLDoubleByte;
			if (Gf.HTMLDocumentOption == 0)
			{
				OptOutputHTML.Checked = true;
			}
			else
			{
				OptOutputRTF.Checked = true;
			}
			RTFFontSize.Value = Gf.HTMLRTFFontSize;
			Gf.GenHTMLDir = Gf.RootEasiSlidesDir + "Html\\";
			WarningLabel.Text = "NOTE: Generate will Delete ALL existing HTML files in: '" + Gf.GenHTMLDir + "'";
			ToolTip1.SetToolTip(WarningLabel, WarningLabel.Text);
			Gf.SetListViewColumns(SubDivideList, 6);
			HtmlItem.Initialise();
			HtmlItem.SplitScreens = false;
		}

		private void LookupSong(DbConnection connection)
		{
			try
			{
				//OleDbConnection connection = new OleDbConnection(Gf.ConnectStringMainDB);

				//DBEngine dBEngine = new DBEngine();// DBEngineClass();
				//Workspace workspace = dBEngine.Workspaces[0];
				//Database database = workspace.OpenDatabase(connection.DataSource, false, false);
				string name = "select * from SONG where songid=" + DataUtil.Right(Gf.DocumentSongs[CurrentSong, 0], Gf.DocumentSongs[CurrentSong, 0].Length - 1);

				using DataTable dt = DbController.GetDataTable(connection, name);
				if (dt.Rows.Count > 0)
				{
					DataRow dr = dt.Rows[0];

					SongTitle = Gf.RTFCheck(DataUtil.GetDataString(dr, "Title_1"));
					SongLyrics = Gf.RTFCheck(DataUtil.GetDataString(dr, "Lyrics"));
					SongFolderNo = DataUtil.GetDataInt(dr, "FolderNo");
					SongTitle2 = Gf.RTFCheck(DataUtil.GetDataString(dr, "Title_2"));
					SongNotations = DataUtil.GetDataString(dr, "msc");
					SongSequence = DataUtil.GetDataString(dr, "Sequence");
					WriterInfo = DataUtil.GetDataString(dr, "Writer");
					SongCapo = DataUtil.GetDataInt(dr, "capo", Minus1IfBlank: true);
					SongKey = DataUtil.GetDataString(dr, "key");
					BookRefInfo = DataUtil.GetDataString(dr, "BOOK_REFERENCE");
					UserRefInfo = DataUtil.GetDataString(dr, "USER_REFERENCE");
					CopyrightInfo = DataUtil.GetDataString(dr, "Copyright");
					CopyrightInfo = Gf.RTFCheck(WriterInfo + (((WriterInfo != "") & (CopyrightInfo != "")) ? "; " : "") + CopyrightInfo);
				}
			}
			catch
			{
				HtmlItem.SongSequence = "";
				HtmlItem.CompleteLyrics = "";
				HtmlItem.Notations = "";
				return;
			}
			HtmlItem.SongSequence = SongSequence;
			HtmlItem.CompleteLyrics = SongLyrics;
			HtmlItem.Notations = SongNotations;
			Gf.FormatDisplayLyrics(ref HtmlItem, PrepareSlides: true, UseStoredSequence: true);
			SongSequence = HtmlItem.SongSequence;
			CurSlide = 1;
		}

		private string CheckHTMLDisplayName(string InFileName)
		{
			Gf.RemoveInvalidDirNameChars(ref InFileName);
			if (!File.Exists(Gf.GenHTMLDir + InFileName + ".htm"))
			{
				return InFileName;
			}
			for (int i = 1; i <= 10000; i++)
			{
				if (!File.Exists(Gf.GenHTMLDir + InFileName + i + ".htm"))
				{
					return InFileName + i;
				}
			}
			return "";
		}

		private void BtnOK_Click(object sender, EventArgs e)
		{
			Gf.HTMLPublisher = DataUtil.Trim(HeadingText0.Text);
			Gf.HTMLWeb = DataUtil.Trim(HeadingText1.Text);
			Gf.HTMLInfo1 = DataUtil.Trim(HeadingText2.Text);
			Gf.HTMLMusicLink = MusicLinkcb.Checked;
			Gf.HTMLShowIndex = ShowindexFilecb.Checked;
			Gf.HTMLShowNumbers = MusicNumberscb.Checked;
			Gf.HTMLShowChorusItalics = ChorusItaliccb.Checked;
			Gf.HTMLShowBookRef = BookRefcb.Checked;
			Gf.HTMLShowUserRef = UserRefcb.Checked;
			Gf.HTMLDoubleByte = DoubleBytecb.Checked;
			Gf.HTMLDocumentOption = ((!OptOutputHTML.Checked) ? 1 : 0);
			Gf.HTMLRTFFontSize = (int)RTFFontSize.Value;
			RegUtil.SaveRegValue("config", "HTML_Publisher", Gf.HTMLPublisher);
			RegUtil.SaveRegValue("config", "HTML_Web", Gf.HTMLWeb);
			RegUtil.SaveRegValue("config", "HTML_Info1", Gf.HTMLInfo1);
			RegUtil.SaveRegValue("config", "HTML_Musiclink", Gf.HTMLMusicLink ? 1 : 0);
			RegUtil.SaveRegValue("config", "HTML_ShowIndex", Gf.HTMLShowIndex ? 1 : 0);
			RegUtil.SaveRegValue("config", "HTML_ShowChorusItalics", Gf.HTMLShowChorusItalics ? 1 : 0);
			RegUtil.SaveRegValue("config", "HTML_ShowNumbers", Gf.HTMLShowNumbers ? 1 : 0);
			RegUtil.SaveRegValue("config", "HTML_ShowBookReference", Gf.HTMLShowBookRef ? 1 : 0);
			RegUtil.SaveRegValue("config", "HTML_ShowUserReference", Gf.HTMLShowUserRef ? 1 : 0);
			RegUtil.SaveRegValue("config", "HTML_DoubleByte", Gf.HTMLDoubleByte ? 1 : 0);
			RegUtil.SaveRegValue("config", "HTML_DocumentOption", Gf.HTMLDocumentOption);
			RegUtil.SaveRegValue("config", "HTML_RTFFontSize", Gf.HTMLRTFFontSize);
			HeadingText0.Text = Gf.HTMLPublisher;
			HeadingText1.Text = Gf.HTMLWeb;
			HeadingText2.Text = Gf.HTMLInfo1;
			Gf.ValidateDir(Gf.GenHTMLDir, CreateDir: true);
			try
			{
				if (Directory.Exists(Gf.GenHTMLDir))
				{
					string[] files = Directory.GetFiles(Gf.GenHTMLDir, "*.htm");
					string[] array = files;
					foreach (string path in array)
					{
						File.Delete(path);
					}
					files = Directory.GetFiles(Gf.GenHTMLDir, "*.rtf");
					array = files;
					foreach (string path in array)
					{
						File.Delete(path);
					}
				}
				WarningLabel.Visible = false;
				StartGeneration();
				if (Gf.HTMLShowIndex)
				{
					Gf.RunProcess(Gf.GenHTMLDir + "index.htm");
				}
			}
			catch
			{
			}
			Cursor = Cursors.Default;
		}

		private bool StartGeneration()
		{
			byte[] array = new byte[1];
			StringBuilder stringBuilder = new StringBuilder();
			string text = DateTime.Now.Date.ToString("dd MMM yyyy");
			int num = 0;
			int hTMLRTFFontSize = Gf.HTMLRTFFontSize;
			int num2 = Gf.HTMLRTFFontSize * 10 / 12;
			Gf.TotalMusicFiles = -1;
			HTML_ShowHeadings[0] = 1;
			HTML_ShowHeadings[1] = 1;
			HTML_ShowHeadings[2] = 0;
			HTML_ShowHeadings[3] = 0;
			NewLine = "<BR>\r\n";
			Gf.RTFNewLine = "\\b0\\i0\\ulnone\\par ";
			Gf.RTFIndent[0] = "\\pard\\fi-1500\\li1500\\tx1100 ";
			Gf.RTFIndent[1] = "\\pard\\fi-900\\li900\\tx500 ";
			Gf.RTFIndent[2] = "\\pard\\li0\\tx500 ";
			RTFMaxTextWidth = 8750;
			Cursor = Cursors.WaitCursor;
			ProgressBar1.Value = 0;
			ProgressBar1.Invalidate();
			try
			{
				int num3 = OptOutputHTML.Checked ? 100 : 50;
				int num4 = OptOutputHTML.Checked ? 250 : 150;
				int num5 = OptOutputHTML.Checked ? 430 : 600;
				int num6 = OptOutputHTML.Checked ? 420 : 530;
				string text2 = OptOutputHTML.Checked ? "" : ",toolbar=yes";
				string text3 = "\r\n<SCRIPT TYPE=\"text/javascript\"><!--\r\nfunction popup(mylink, windowname) \r\n{\r\nif (! window.focus)return true;\r\nvar href;\r\nif (typeof(mylink) == 'string')\r\n href=mylink;\r\nelse\r\n href=mylink.href;\r\nwindow.open(href, windowname, 'width=" + num5 + ",height=" + num6 + text2 + ", left=" + num4 + ",top=" + num3 + ", resizable=yes, scrollbars=yes');\r\nreturn false;\r\n}\r\n//-->\r\n</SCRIPT>\r\n";
				string text4 = "<META NAME=\"description\" CONTENT=\"" + Gf.HTMLInfo1 + ((Gf.HTMLInfo1 != "") ? " - " : "") + "Auto-Generated by EasiSlides\">";
				stringBuilder.Append(EasiSlidesInfoComments + EasiSlidesInfoCommentsEnd + "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"><html><head><title>" + Gf.HTMLPublisher + "</title>" + text4 + "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">" + text3 + "</head><body>" + ((Gf.HTMLPublisher == "") ? "" : ("<font size=\"4\"><b><a href=" + Gf.HTMLWeb + ">" + Gf.HTMLPublisher + "</a></b>" + NewLine + NewLine)) + ((Gf.HTMLInfo1 == "") ? "" : (Gf.HTMLInfo1 + NewLine + NewLine)) + "Dated: " + text + "</P><ul><li><b>To see the contents:</b> Click on the desired title and the contents will appear in a new window.</a>");
				stringBuilder.Append((Gf.HTMLMusicLink ? "<li><b>To play a music file:</b> If <font color=\"#FF00FF\">(Music)</font> appears beside a title, you can click on it to play the music file for that title</a>" : "") + "</P></ul>");
				string text5 = "";
				string text8 = "";
				int num7 = 0;
				SongFolderLog = new int[Gf.TotalPraiseBookItems];

				using DbConnection connection = DbController.GetDbConnection(Gf.ConnectStringMainDB);
				for (int i = 0; i < Gf.TotalPraiseBookItems; i++)
				{
					num7 = (i + 1) * 100 / Gf.TotalPraiseBookItems;
					ProgressBar1.Value = ((num7 > 100) ? 100 : num7);
					CurrentSong = i + 1;
					LookupSong(connection);
					SongFolderLog[i] = SongFolderNo;
					string songTitle = SongTitle;
					string text9 = "";
					if (Gf.HTMLShowNumbers)
					{
						text5 = ((!Gf.UseSongNumbers) ? (Convert.ToString(CurrentSong) + ". ") : (Gf.DocumentSongs[CurrentSong, 4] + ". "));
					}
					text9 = DataUtil.HexString(songTitle);
					SongFolderLog[i] = SongFolderNo;
					int num8 = 0;
					for (int j = 1; j <= HtmlItem.TotalSlides; j++)
					{
						if (HtmlItem.Slide[j, 0] == 0)
						{
							num8 = j;
							num = 1;
						}
						if ((num8 > 0) & (HtmlItem.Slide[j, 0] < 0))
						{
							num++;
						}
					}
					ChorusDone = false;
					string text10 = CheckHTMLDisplayName(text9);
					stringBuilder.Append("\r\n<li><b>" + text5 + "</b><a href=\"" + text10 + (OptOutputHTML.Checked ? ".htm" : ".rtf") + "\" onClick=\"return popup(this, 'A')\">" + SongTitle + "</a>");
					text8 = "";
					if (Gf.HTMLMusicLink && Gf.MusicFound(SongTitle, SongTitle2, StoreDirPath: true))
					{
						text8 = Gf.Html_MusicDisplayName(SongTitle, SongTitle2, Gf.GenHTMLDir);
						if (text8 != "")
						{
							stringBuilder.Append(" <a href=" + '"' + text8 + '"' + "><font color=\"#FF00FF\">(Music)</font></a></li>");
						}
					}
					if (OptOutputHTML.Checked)
					{
						GenerateOneHTMLFile(i, text10, num);
					}
					else if (OptOutputRTF.Checked)
					{
						Font mainFont = new Font(Gf.ShowFontName[SongFolderNo, 0], hTMLRTFFontSize);
						Font mainFontR = new Font(Gf.ShowFontName[SongFolderNo, 1], hTMLRTFFontSize);
						Font notationsFont = new Font(Gf.ShowFontName[SongFolderNo, 0], num2);
						Font notationsFontR = new Font(Gf.ShowFontName[SongFolderNo, 1], num2);
						GenerateOneRTFFile(i, text10, num, mainFont, mainFontR, notationsFont, notationsFontR);
					}
				}
				FileUtil.CreateNewFile(Gf.GenHTMLDir + "index.htm", (!Gf.HTMLDoubleByte) ? FileUtil.FileContentsType.Ascii_Html : FileUtil.FileContentsType.DoubleByte, stringBuilder.ToString());
				ProgressBar1.Value = 100;
			}
			catch
			{
			}
			Cursor = Cursors.Default;
			return true;
		}

		private void GenerateOneHTMLFile(int InCount, string OutputFileName, int InChorusSlideCount)
		{
			StringBuilder stringBuilder = new StringBuilder();
			string text = "\r\n<SCRIPT TYPE=\"text/javascript\"><!--\r\nwindow.focus();\r\n//-->\r\n</SCRIPT>\r\n";
			string text2 = "\r\n<SCRIPT TYPE=\"text/javascript\"><!--\r\nfunction ClipBoard() \r\n{\r\nholdtext.innerText = copytext.innerText;\r\nCopied = holdtext.createTextRange();\r\nCopied.execCommand(\"Copy\");\r\n}\r\n</SCRIPT> ";
			string text3 = "\r\n<TEXTAREA ID=\"holdtext\" STYLE=\"display:none;\"></TEXTAREA><BUTTON onClick=\"ClipBoard();\">Copy to Clipboard</BUTTON> ";
			try
			{
				string text4 = (SongTitle2 == "") ? SongTitle : (SongTitle + " (" + SongTitle2 + ")");
				stringBuilder.Append("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"><html><head><title>" + text4 + "</title><meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">" + text + text2 + "</head><font size=\"4\">" + text3 + NewLine);
				stringBuilder.Append(NewLine + "<SPAN ID=\"copytext\"> <div align=\"center\"><b><u>" + SongTitle + "</u></b>" + NewLine);
				string str2;
				for (int i = 1; i <= HtmlItem.TotalSlides; i++)
				{
					int curFormat = CurFormat;
					bool flag = false;
					ShowFirstLineOnly = false;
					CurSlide = i;
					string str = "";
					if (HtmlItem.Slide[CurSlide, 0] == 0)
					{
						if (!ChorusDone)
						{
							ChorusDone = true;
						}
						else
						{
							ShowFirstLineOnly = true;
						}
						CurFormat = 4;
						flag = true;
					}
					else if (HtmlItem.Slide[CurSlide, 0] > 0)
					{
						if (((HTML_ShowHeadings[1] > 0) & HtmlItem.VersePresent[2]) && HtmlItem.Slide[CurSlide, 0] != 101)
						{
							str = Gf.VerseTitle[HtmlItem.Slide[CurSlide, 0]] + NewLine;
						}
						CurFormat = 3;
						flag = true;
					}
					if (flag)
					{
					}
					if (HtmlItem.Slide[CurSlide, 2] > 0)
					{
						str2 = str + AddtoHtmlFile(HtmlItem.Slide[CurSlide, 1], HtmlItem.Slide[CurSlide, 2]);
						stringBuilder.Append(((CurFormat == 4) ? "" : NewLine) + str2 + ((CurFormat == 4) ? "" : ((HtmlItem.Slide[CurSlide, 4] > 0) ? "" : NewLine)));
						str = "";
					}
					if (HtmlItem.Slide[CurSlide, 4] > 0)
					{
						str2 = str + AddtoHtmlFile(HtmlItem.Slide[CurSlide, 3], HtmlItem.Slide[CurSlide, 4]);
						stringBuilder.Append(((CurFormat == 4) ? "" : NewLine) + str2 + ((CurFormat == 4) ? "" : NewLine));
					}
					if (ShowFirstLineOnly)
					{
						i += InChorusSlideCount - 1;
					}
				}
				if (CopyrightInfo != "")
				{
					stringBuilder.Append("</p><font size=\"2\">" + CopyrightInfo);
				}
				str2 = "";
				if ((BookRefInfo != "") & Gf.HTMLShowBookRef)
				{
					stringBuilder.Append(((CopyrightInfo == "") ? "</p><font size=\"2\">" : "<BR>") + BookRefInfo);
				}
				str2 = "";
				if ((UserRefInfo != "") & Gf.HTMLShowUserRef)
				{
					stringBuilder.Append((((CopyrightInfo == "") & (BookRefInfo == "")) ? "</p><font size=\"2\">" : "<BR>") + UserRefInfo);
				}
				stringBuilder.Append("</p>&nbsp;</div></SPAN>");
				FileUtil.CreateNewFile(Gf.GenHTMLDir + OutputFileName + ".htm", (!Gf.HTMLDoubleByte) ? FileUtil.FileContentsType.Ascii_Html : FileUtil.FileContentsType.DoubleByte, stringBuilder.ToString());
				stringBuilder.Remove(0, stringBuilder.Length);
			}
			catch
			{
			}
		}

		private string AddtoHtmlFile(int StartLoc, int EndLoc)
		{
			string text = "";
			if (ShowFirstLineOnly)
			{
				text = HtmlItem.LyricsAndNotationsList.Items[StartLoc].SubItems[2].Text + " ..." + NewLine;
			}
			else
			{
				for (int i = StartLoc; i <= EndLoc; i++)
				{
					text = text + HtmlItem.LyricsAndNotationsList.Items[i].SubItems[2].Text + NewLine;
				}
			}
			text = DataUtil.TrimEnd(text);
			if (CurFormat == 4)
			{
				return "<blockquote>" + (Gf.HTMLShowChorusItalics ? "<em>" : "") + text + (Gf.HTMLShowChorusItalics ? "</em>" : "") + "</blockquote>";
			}
			return text;
		}

		private void GenerateOneRTFFile(int InCount, string OutputFileName, int InChorusSlideCount, Font MainFont, Font MainFontR2, Font NotationsFont, Font NotationsFontR2)
		{
			StringBuilder stringBuilder = new StringBuilder();
			MainHeaderInfo1 = "{\\rtf1\\ansi\\ansicpg1252\\deff0\\deflang1033{\\fonttbl{\\f0\\fnil\\fcharset0 " + MainFont.Name + ";}{\\f1\\fnil\\fcharset0 " + MainFontR2.Name + ";}}\\viewkind1\\uc1\\pard\\f0\\fs" + Convert.ToString(MainFont.Size * 2f) + "\\margr600\\margl1000\\margt900\\margb1000 ";

			using StreamWriter streamWriter = new StreamWriter($"{Gf.GenHTMLDir}{OutputFileName}.rtf", append: false, FileUtil.Utf8WithBom);
			try
			{
				streamWriter.AutoFlush = true;
				streamWriter.Write(MainHeaderInfo1);
				streamWriter.Write(DataUtil.UnicodeToAscii_RTF("\\b1\\ul " + SongTitle + "\\b0\\ulnone " + Gf.RTFNewLine));
				if (SongKey != "" || SongCapo > 0)
				{
					SongKey = ((SongKey != "") ? ("Key: " + SongKey + "  ") : "");
					string text = (SongCapo > 0) ? ("Capo " + SongCapo) : "";
					streamWriter.Write(DataUtil.UnicodeToAscii_RTF(Gf.RTFNewLine + "\\b0\\ulnone " + SongKey + text + "\\b0\\ulnone "));
				}
				streamWriter.Write(DataUtil.UnicodeToAscii_RTF(Gf.RTFNewLine));
				bool flag = false;
				for (int i = 1; i <= HtmlItem.TotalSlides; i++)
				{
					if (HtmlItem.Slide[CurSlide, 0] == 0)
					{
						flag = true;
						i = HtmlItem.TotalSlides + 1;
					}
					else if (((HTML_ShowHeadings[0] > 0) & HtmlItem.VersePresent[2]) && HtmlItem.Slide[CurSlide, 0] != 101 && Gf.VerseTitle[HtmlItem.Slide[CurSlide, 0]] != "")
					{
						flag = true;
						i = HtmlItem.TotalSlides + 1;
					}
				}
				string str;
				for (int i = 1; i <= HtmlItem.TotalSlides; i++)
				{
					int curFormat = CurFormat;
					ShowFirstLineOnly = false;
					CurSlide = i;
					string text2 = "";
					if (HtmlItem.Slide[CurSlide, 0] == 0)
					{
						text2 = "\\par ";
						if (HTML_ShowHeadings[0] > 0 && !ChorusDone)
						{
							text2 += Gf.FolderLyricsHeading[SongFolderNo, 0];
							text2 = ((text2 != "") ? text2 : "");
						}
						if (!ChorusDone)
						{
							ChorusDone = true;
						}
						else
						{
							ShowFirstLineOnly = true;
						}
						CurFormat = 4;
					}
					else if (HtmlItem.Slide[CurSlide, 0] > 0)
					{
						if (((HTML_ShowHeadings[1] > 0) & HtmlItem.VersePresent[2]) && HtmlItem.Slide[CurSlide, 0] != 101)
						{
							text2 = Gf.VerseTitle[HtmlItem.Slide[CurSlide, 0]];
						}
						CurFormat = 3;
					}
					if (HtmlItem.Slide[CurSlide, 2] > 0)
					{
						str = AddtoFTPFile(HtmlItem.Slide[CurSlide, 1], HtmlItem.Slide[CurSlide, 2], MainFont, NotationsFont, 0, CurFormat == 4 || flag, text2);
						stringBuilder.Append(((CurFormat == 4) ? "" : Gf.RTFNewLine) + str);
						text2 = "";
					}
					if (HtmlItem.Slide[CurSlide, 4] > 0)
					{
						str = AddtoFTPFile(HtmlItem.Slide[CurSlide, 3], HtmlItem.Slide[CurSlide, 4], MainFontR2, NotationsFontR2, 1, CurFormat == 4 || flag, text2);
						stringBuilder.Append(((CurFormat == 4) ? "" : Gf.RTFNewLine) + str);
					}
					if (ShowFirstLineOnly)
					{
						i += InChorusSlideCount - 1;
					}
				}
				stringBuilder.Append(Gf.RTFNewLine + Gf.RTFIndent[2]);
				if (CopyrightInfo != "")
				{
					stringBuilder.Append(Gf.RTFNewLine + CopyrightInfo);
				}
				str = "";
				if ((BookRefInfo != "") & Gf.HTMLShowBookRef)
				{
					stringBuilder.Append(Gf.RTFNewLine + BookRefInfo);
				}
				str = "";
				if ((UserRefInfo != "") & Gf.HTMLShowUserRef)
				{
					stringBuilder.Append(Gf.RTFNewLine + UserRefInfo);
				}
				streamWriter.Write(DataUtil.UnicodeToAscii_RTF(stringBuilder.ToString()));
				streamWriter.Write("}");
				//streamWriter.Flush();
				//streamWriter.Close();
			}
			catch
			{
				//streamWriter.Flush();
				//streamWriter.Close();
				MessageBox.Show("Error generating listing " + OutputFileName + ". Document might be in use.");
			}
		}

		private string AddtoFTPFile(int StartLoc, int EndLoc, Font MainFont, Font NotationsFont, int RegionNum, bool HeadingPresent, string HeadingText)
		{
			string text = "";
			string text2 = "";
			string text3 = "";
			string text4 = "\\f" + RegionNum + "\\fs" + Convert.ToString(MainFont.Size * 2f);
			string str = "\\f" + RegionNum + "\\fs" + Convert.ToString(NotationsFont.Size * 2f);
			string text5 = HeadingPresent ? Gf.RTFTab : "";
			NotationsPresent = false;
			if (ShowNotations)
			{
				for (int i = StartLoc; i <= EndLoc; i++)
				{
					if (HtmlItem.LyricsAndNotationsList.Items[i].SubItems[3].Text != "")
					{
						NotationsPresent = true;
						i = EndLoc;
					}
				}
			}
			if (ShowFirstLineOnly)
			{
				text2 = "\\par " + text5 + HtmlItem.LyricsAndNotationsList.Items[StartLoc].SubItems[2].Text + " ...\\par ";
			}
			else
			{
				for (int i = StartLoc; i <= EndLoc; i++)
				{
					text3 = HtmlItem.LyricsAndNotationsList.Items[i].SubItems[2].Text;
					if (NotationsPresent)
					{
						text = HtmlItem.LyricsAndNotationsList.Items[i].SubItems[3].Text;
						Gf.SubDivideTextAndNotations(text3, text, MainFont, NotationsFont, ref SubDivideList, RTFMaxTextWidth);
						text = str + SubDivideList.Items[0].SubItems[1].Text + "\\par " + text5;
					}
					string text6 = text2;
					text2 = text6 + text5 + text + text4 + text3 + "\\par ";
				}
				text2 = HeadingText + text2;
			}
			text2 = DataUtil.TrimEnd(text2);
			if (CurFormat == 4)
			{
				return Gf.RTFIndent[0] + (Gf.HTMLShowChorusItalics ? "\\i " : "") + text2 + (Gf.HTMLShowChorusItalics ? "\\i0" : "");
			}
			return (HeadingPresent ? Gf.RTFIndent[1] : Gf.RTFIndent[2]) + text2;
		}

		            }
}
