//using NetOffice.DAOApi;
//using NetOffice.DAOApi.Enums;

using Easislides.Util;
using System;
using System.ComponentModel;
using System.Data;
//using System.Data.SQLite;
using System.Drawing;
using System.IO;
using System.Text;
using System.Windows.Forms;

using Easislides.SQLite;
using Easislides.Module;
#if SQLite
using DbConnection = System.Data.SQLite.SQLiteConnection;
#elif MariaDB
using DbConnection = MySql.Data.MySqlClient.MySqlConnection;
using DbDataAdapter = MySql.Data.MySqlClient.MySqlDataAdapter;
using DbCommandBuilder = MySql.Data.MySqlClient.MySqlCommandBuilder;
using DbCommand = MySql.Data.MySqlClient.MySqlCommand;
using DbDataReader = MySql.Data.MySqlClient.MySqlDataReader;
using DbTransaction = MySql.Data.MySqlClient.MySqlTransaction;
#endif

namespace Easislides
{
    public class FrmGenerateHtml : Form
	{
		private const string EasiSlidesInfo = "Auto-Generated by EasiSlides";

		private int[] SongFolderLog = new int[1];

		private int[,] FolderFNum = new int[gf.MAXSONGSFOLDERS, 1];

		private int CurrentSong;

		private int CurSlide;

		private bool ChorusDone;

		private bool ShowFirstLineOnly;

		private string CopyrightInfo;

		private string UserRefInfo;

		private string BookRefInfo;

		private string WriterInfo;

		private string SongTitle2;

		private string SongTitle;

		private int SongCapo;

		private string SongKey;

		private int SongFolderNo;

		private string SongNotations;

		private string SongLyrics;

		private string SongSequence;

		private bool NotationsPresent = false;

		private bool ShowNotations = true;

		private int CurFormat;

		private int[] HTML_ShowHeadings = new int[4];

		private string NewLine;

		private SongSettings HtmlItem = new SongSettings();

		private string EasiSlidesInfoComments = "<!-- Auto-Generated by EasiSlides";

		private string EasiSlidesInfoCommentsEnd = " -->\r\n";

		private string MainHeaderInfo1 = "{\\rtf1\\ansi\\ansicpg1252\\deff0\\deflang1033{\\fonttbl{\\f0\\fnil\\fcharset0 Microsoft Sans Serif;}}\\viewkind1\\uc1\\pard\\f0\\fs24\\margr800\\margl1200\\margt800\\margb800 ";

		private ListView SubDivideList = new ListView();

		private int RTFMaxTextWidth;

		private IContainer components = null;

		private TextBox HeadingText0;

		private Label label1;

		private Label label2;

		private TextBox HeadingText1;

		private Label label3;

		private TextBox HeadingText2;

		private CheckBox MusicLinkcb;

		private CheckBox MusicNumberscb;

		private CheckBox ShowindexFilecb;

		private CheckBox BookRefcb;

		private CheckBox UserRefcb;

		private ProgressBar ProgressBar1;

		private Label WarningLabel;

		private ToolTip ToolTip1;

		private Button BtnCancel;

		private Button BtnOK;

		private CheckBox DoubleBytecb;

		private RadioButton OptOutputHTML;

		private RadioButton OptOutputRTF;

		private GroupBox groupBox1;

		private CheckBox ChorusItaliccb;

		private NumericUpDown RTFFontSize;

		private Label label4;

		public FrmGenerateHtml()
		{
			InitializeComponent();
		}

		private void FrmGenerateHTML_Load(object sender, EventArgs e)
		{
			Text = "Generate HTML files for " + gf.CurPraiseBook;
			HeadingText0.Text = RegUtil.GetRegValue("config", "HTML_Publisher", "");
			HeadingText1.Text = RegUtil.GetRegValue("config", "HTML_Web", "");
			HeadingText2.Text = RegUtil.GetRegValue("config", "HTML_Info1", "");
			gf.HTMLShowNumbers = ((RegUtil.GetRegValue("config", "HTML_ShowNumbers", 0) == 1) ? true : false);
			gf.HTMLShowChorusItalics = ((RegUtil.GetRegValue("config", "HTML_ShowChorusItalics", 1) == 1) ? true : false);
			gf.HTMLMusicLink = ((RegUtil.GetRegValue("config", "HTML_Musiclink", 1) == 1) ? true : false);
			gf.HTMLShowIndex = ((RegUtil.GetRegValue("config", "HTML_ShowIndex", 1) == 1) ? true : false);
			gf.HTMLShowBookRef = ((RegUtil.GetRegValue("config", "HTML_ShowBookReference", 1) == 1) ? true : false);
			gf.HTMLShowUserRef = ((RegUtil.GetRegValue("config", "HTML_ShowUserReference", 1) == 1) ? true : false);
			gf.HTMLDoubleByte = ((RegUtil.GetRegValue("config", "HTML_DoubleByte", 0) == 1) ? true : false);
			gf.HTMLDocumentOption = RegUtil.GetRegValue("config", "HTML_DocumentOption", 0);
			gf.HTMLDocumentOption = ((gf.HTMLDocumentOption >= 0 && gf.HTMLDocumentOption <= 1) ? gf.HTMLDocumentOption : 0);
			gf.HTMLRTFFontSize = RegUtil.GetRegValue("config", "HTML_RTFFontSize", 12);
			gf.HTMLRTFFontSize = ((gf.HTMLRTFFontSize < 6 || gf.HTMLRTFFontSize > 99) ? 12 : gf.HTMLRTFFontSize);
			MusicLinkcb.Checked = gf.HTMLMusicLink;
			ShowindexFilecb.Checked = gf.HTMLShowIndex;
			MusicNumberscb.Checked = gf.HTMLShowNumbers;
			ChorusItaliccb.Checked = gf.HTMLShowChorusItalics;
			BookRefcb.Checked = gf.HTMLShowBookRef;
			UserRefcb.Checked = gf.HTMLShowUserRef;
			DoubleBytecb.Checked = gf.HTMLDoubleByte;
			if (gf.HTMLDocumentOption == 0)
			{
				OptOutputHTML.Checked = true;
			}
			else
			{
				OptOutputRTF.Checked = true;
			}
			RTFFontSize.Value = gf.HTMLRTFFontSize;
			gf.GenHTMLDir = gf.RootEasiSlidesDir + "Html\\";
			WarningLabel.Text = "NOTE: Generate will Delete ALL existing HTML files in: '" + gf.GenHTMLDir + "'";
			ToolTip1.SetToolTip(WarningLabel, WarningLabel.Text);
			gf.SetListViewColumns(SubDivideList, 6);
			HtmlItem.Initialise();
			HtmlItem.SplitScreens = false;
		}


		private void LookupSong(DbConnection connection)
		{
			try
			{
				//OleDbConnection connection = new OleDbConnection(gf.ConnectStringMainDB);
                
				//DBEngine dBEngine = new DBEngine();// DBEngineClass();
				//Workspace workspace = dBEngine.Workspaces[0];
				//Database database = workspace.OpenDatabase(connection.DataSource, false, false);
				string name = "select * from SONG where songid=" + DataUtil.Right(gf.DocumentSongs[CurrentSong, 0], gf.DocumentSongs[CurrentSong, 0].Length - 1);

				using DataTable dt = DbController.GetDataTable(connection, name);
				if (dt.Rows.Count > 0)
				{
					DataRow dr = dt.Rows[0];

					SongTitle = gf.RTFCheck(DataUtil.GetDataString(dr, "Title_1"));
					SongLyrics = gf.RTFCheck(DataUtil.GetDataString(dr, "Lyrics"));
					SongFolderNo = DataUtil.GetDataInt(dr, "FolderNo");
					SongTitle2 = gf.RTFCheck(DataUtil.GetDataString(dr, "Title_2"));
					SongNotations = DataUtil.GetDataString(dr, "msc");
					SongSequence = DataUtil.GetDataString(dr, "Sequence");
					WriterInfo = DataUtil.GetDataString(dr, "Writer");
					SongCapo = DataUtil.GetDataInt(dr, "capo", Minus1IfBlank: true);
					SongKey = DataUtil.GetDataString(dr, "key");
					BookRefInfo = DataUtil.GetDataString(dr, "BOOK_REFERENCE");
					UserRefInfo = DataUtil.GetDataString(dr, "USER_REFERENCE");
					CopyrightInfo = DataUtil.GetDataString(dr, "Copyright");
					CopyrightInfo = gf.RTFCheck(WriterInfo + (((WriterInfo != "") & (CopyrightInfo != "")) ? "; " : "") + CopyrightInfo);
				}
			}
			catch
			{
				HtmlItem.SongSequence = "";
				HtmlItem.CompleteLyrics = "";
				HtmlItem.Notations = "";
				return;
			}
			HtmlItem.SongSequence = SongSequence;
			HtmlItem.CompleteLyrics = SongLyrics;
			HtmlItem.Notations = SongNotations;
			gf.FormatDisplayLyrics(ref HtmlItem, PrepareSlides: true, UseStoredSequence: true);
			SongSequence = HtmlItem.SongSequence;
			CurSlide = 1;
		}

		private string CheckHTMLDisplayName(string InFileName)
		{
			gf.RemoveInvalidDirNameChars(ref InFileName);
			if (!File.Exists(gf.GenHTMLDir + InFileName + ".htm"))
			{
				return InFileName;
			}
			for (int i = 1; i <= 10000; i++)
			{
				if (!File.Exists(gf.GenHTMLDir + InFileName + i + ".htm"))
				{
					return InFileName + i;
				}
			}
			return "";
		}

		private void BtnOK_Click(object sender, EventArgs e)
		{
			gf.HTMLPublisher = DataUtil.Trim(HeadingText0.Text);
			gf.HTMLWeb = DataUtil.Trim(HeadingText1.Text);
			gf.HTMLInfo1 = DataUtil.Trim(HeadingText2.Text);
			gf.HTMLMusicLink = MusicLinkcb.Checked;
			gf.HTMLShowIndex = ShowindexFilecb.Checked;
			gf.HTMLShowNumbers = MusicNumberscb.Checked;
			gf.HTMLShowChorusItalics = ChorusItaliccb.Checked;
			gf.HTMLShowBookRef = BookRefcb.Checked;
			gf.HTMLShowUserRef = UserRefcb.Checked;
			gf.HTMLDoubleByte = DoubleBytecb.Checked;
			gf.HTMLDocumentOption = ((!OptOutputHTML.Checked) ? 1 : 0);
			gf.HTMLRTFFontSize = (int)RTFFontSize.Value;
			RegUtil.SaveRegValue("config", "HTML_Publisher", gf.HTMLPublisher);
			RegUtil.SaveRegValue("config", "HTML_Web", gf.HTMLWeb);
			RegUtil.SaveRegValue("config", "HTML_Info1", gf.HTMLInfo1);
			RegUtil.SaveRegValue("config", "HTML_Musiclink", gf.HTMLMusicLink ? 1 : 0);
			RegUtil.SaveRegValue("config", "HTML_ShowIndex", gf.HTMLShowIndex ? 1 : 0);
			RegUtil.SaveRegValue("config", "HTML_ShowChorusItalics", gf.HTMLShowChorusItalics ? 1 : 0);
			RegUtil.SaveRegValue("config", "HTML_ShowNumbers", gf.HTMLShowNumbers ? 1 : 0);
			RegUtil.SaveRegValue("config", "HTML_ShowBookReference", gf.HTMLShowBookRef ? 1 : 0);
			RegUtil.SaveRegValue("config", "HTML_ShowUserReference", gf.HTMLShowUserRef ? 1 : 0);
			RegUtil.SaveRegValue("config", "HTML_DoubleByte", gf.HTMLDoubleByte ? 1 : 0);
			RegUtil.SaveRegValue("config", "HTML_DocumentOption", gf.HTMLDocumentOption);
			RegUtil.SaveRegValue("config", "HTML_RTFFontSize", gf.HTMLRTFFontSize);
			HeadingText0.Text = gf.HTMLPublisher;
			HeadingText1.Text = gf.HTMLWeb;
			HeadingText2.Text = gf.HTMLInfo1;
			gf.ValidateDir(gf.GenHTMLDir, CreateDir: true);
			try
			{
				if (Directory.Exists(gf.GenHTMLDir))
				{
					string[] files = Directory.GetFiles(gf.GenHTMLDir, "*.htm");
					string[] array = files;
					foreach (string path in array)
					{
						File.Delete(path);
					}
					files = Directory.GetFiles(gf.GenHTMLDir, "*.rtf");
					array = files;
					foreach (string path in array)
					{
						File.Delete(path);
					}
				}
				WarningLabel.Visible = false;
				StartGeneration();
				if (gf.HTMLShowIndex)
				{
					gf.RunProcess(gf.GenHTMLDir + "index.htm");
				}
			}
			catch
			{
			}
			Cursor = Cursors.Default;
		}

		private bool StartGeneration()
		{
			byte[] array = new byte[1];
			StringBuilder stringBuilder = new StringBuilder();
			string text = DateTime.Now.Date.ToString("dd MMM yyyy");
			int num = 0;
			int hTMLRTFFontSize = gf.HTMLRTFFontSize;
			int num2 = gf.HTMLRTFFontSize * 10 / 12;
			gf.TotalMusicFiles = -1;
			HTML_ShowHeadings[0] = 1;
			HTML_ShowHeadings[1] = 1;
			HTML_ShowHeadings[2] = 0;
			HTML_ShowHeadings[3] = 0;
			NewLine = "<BR>\r\n";
			gf.RTFNewLine = "\\b0\\i0\\ulnone\\par ";
			gf.RTFIndent[0] = "\\pard\\fi-1500\\li1500\\tx1100 ";
			gf.RTFIndent[1] = "\\pard\\fi-900\\li900\\tx500 ";
			gf.RTFIndent[2] = "\\pard\\li0\\tx500 ";
			RTFMaxTextWidth = 8750;
			Cursor = Cursors.WaitCursor;
			ProgressBar1.Value = 0;
			ProgressBar1.Invalidate();
			try
			{
				int num3 = OptOutputHTML.Checked ? 100 : 50;
				int num4 = OptOutputHTML.Checked ? 250 : 150;
				int num5 = OptOutputHTML.Checked ? 430 : 600;
				int num6 = OptOutputHTML.Checked ? 420 : 530;
				string text2 = OptOutputHTML.Checked ? "" : ",toolbar=yes";
				string text3 = "\r\n<SCRIPT TYPE=\"text/javascript\"><!--\r\nfunction popup(mylink, windowname) \r\n{\r\nif (! window.focus)return true;\r\nvar href;\r\nif (typeof(mylink) == 'string')\r\n href=mylink;\r\nelse\r\n href=mylink.href;\r\nwindow.open(href, windowname, 'width=" + num5 + ",height=" + num6 + text2 + ", left=" + num4 + ",top=" + num3 + ", resizable=yes, scrollbars=yes');\r\nreturn false;\r\n}\r\n//-->\r\n</SCRIPT>\r\n";
				string text4 = "<META NAME=\"description\" CONTENT=\"" + gf.HTMLInfo1 + ((gf.HTMLInfo1 != "") ? " - " : "") + "Auto-Generated by EasiSlides\">";
				stringBuilder.Append(EasiSlidesInfoComments + EasiSlidesInfoCommentsEnd + "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"><html><head><title>" + gf.HTMLPublisher + "</title>" + text4 + "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">" + text3 + "</head><body>" + ((gf.HTMLPublisher == "") ? "" : ("<font size=\"4\"><b><a href=" + gf.HTMLWeb + ">" + gf.HTMLPublisher + "</a></b>" + NewLine + NewLine)) + ((gf.HTMLInfo1 == "") ? "" : (gf.HTMLInfo1 + NewLine + NewLine)) + "Dated: " + text + "</P><ul><li><b>To see the contents:</b> Click on the desired title and the contents will appear in a new window.</a>");
				stringBuilder.Append((gf.HTMLMusicLink ? "<li><b>To play a music file:</b> If <font color=\"#FF00FF\">(Music)</font> appears beside a title, you can click on it to play the music file for that title</a>" : "") + "</P></ul>");
				string text5 = "";
				string text6 = "";
				string text7 = "";
				string text8 = "";
				int num7 = 0;
				SongFolderLog = new int[gf.TotalPraiseBookItems];

				using DbConnection connection = DbController.GetDbConnection(gf.ConnectStringMainDB);
				for (int i = 0; i < gf.TotalPraiseBookItems; i++)
				{
					num7 = (i + 1) * 100 / gf.TotalPraiseBookItems;
					ProgressBar1.Value = ((num7 > 100) ? 100 : num7);
					CurrentSong = i + 1;
					LookupSong(connection);
					SongFolderLog[i] = SongFolderNo;
					string songTitle = SongTitle;
					bool flag = false;
					string text9 = "";
					if (gf.HTMLShowNumbers)
					{
						text5 = ((!gf.UseSongNumbers) ? (Convert.ToString(CurrentSong) + ". ") : (gf.DocumentSongs[CurrentSong, 4] + ". "));
					}
					text9 = DataUtil.HexString(songTitle);
					SongFolderLog[i] = SongFolderNo;
					int num8 = 0;
					for (int j = 1; j <= HtmlItem.TotalSlides; j++)
					{
						if (HtmlItem.Slide[j, 0] == 0)
						{
							num8 = j;
							num = 1;
						}
						if ((num8 > 0) & (HtmlItem.Slide[j, 0] < 0))
						{
							num++;
						}
					}
					int num9 = 0;
					ChorusDone = false;
					string text10 = CheckHTMLDisplayName(text9);
					stringBuilder.Append("\r\n<li><b>" + text5 + "</b><a href=\"" + text10 + (OptOutputHTML.Checked ? ".htm" : ".rtf") + "\" onClick=\"return popup(this, 'A')\">" + SongTitle + "</a>");
					text8 = "";
					if (gf.HTMLMusicLink && gf.MusicFound(SongTitle, SongTitle2, StoreDirPath: true))
					{
						text8 = gf.Html_MusicDisplayName(SongTitle, SongTitle2, gf.GenHTMLDir);
						if (text8 != "")
						{
							stringBuilder.Append(" <a href=" + '"' + text8 + '"' + "><font color=\"#FF00FF\">(Music)</font></a></li>");
						}
					}
					if (OptOutputHTML.Checked)
					{
						GenerateOneHTMLFile(i, text10, num);
					}
					else if (OptOutputRTF.Checked)
					{
						Font mainFont = new Font(gf.ShowFontName[SongFolderNo, 0], hTMLRTFFontSize);
						Font mainFontR = new Font(gf.ShowFontName[SongFolderNo, 1], hTMLRTFFontSize);
						Font notationsFont = new Font(gf.ShowFontName[SongFolderNo, 0], num2);
						Font notationsFontR = new Font(gf.ShowFontName[SongFolderNo, 1], num2);
						GenerateOneRTFFile(i, text10, num, mainFont, mainFontR, notationsFont, notationsFontR);
					}
				}
				FileUtil.CreateNewFile(gf.GenHTMLDir + "index.htm", (!gf.HTMLDoubleByte) ? FileUtil.FileContentsType.Ascii_Html : FileUtil.FileContentsType.DoubleByte, stringBuilder.ToString());
				ProgressBar1.Value = 100;
			}
			catch
			{
			}
			Cursor = Cursors.Default;
			return true;
		}

		private void GenerateOneHTMLFile(int InCount, string OutputFileName, int InChorusSlideCount)
		{
			StringBuilder stringBuilder = new StringBuilder();
			string text = "\r\n<SCRIPT TYPE=\"text/javascript\"><!--\r\nwindow.focus();\r\n//-->\r\n</SCRIPT>\r\n";
			string text2 = "\r\n<SCRIPT TYPE=\"text/javascript\"><!--\r\nfunction ClipBoard() \r\n{\r\nholdtext.innerText = copytext.innerText;\r\nCopied = holdtext.createTextRange();\r\nCopied.execCommand(\"Copy\");\r\n}\r\n</SCRIPT> ";
			string text3 = "\r\n<TEXTAREA ID=\"holdtext\" STYLE=\"display:none;\"></TEXTAREA><BUTTON onClick=\"ClipBoard();\">Copy to Clipboard</BUTTON> ";
			try
			{
				string text4 = (SongTitle2 == "") ? SongTitle : (SongTitle + " (" + SongTitle2 + ")");
				stringBuilder.Append("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"><html><head><title>" + text4 + "</title><meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">" + text + text2 + "</head><font size=\"4\">" + text3 + NewLine);
				stringBuilder.Append(NewLine + "<SPAN ID=\"copytext\"> <div align=\"center\"><b><u>" + SongTitle + "</u></b>" + NewLine);
				string str2;
				for (int i = 1; i <= HtmlItem.TotalSlides; i++)
				{
					int curFormat = CurFormat;
					bool flag = false;
					ShowFirstLineOnly = false;
					CurSlide = i;
					string str = "";
					if (HtmlItem.Slide[CurSlide, 0] == 0)
					{
						if (!ChorusDone)
						{
							ChorusDone = true;
						}
						else
						{
							ShowFirstLineOnly = true;
						}
						CurFormat = 4;
						flag = true;
					}
					else if (HtmlItem.Slide[CurSlide, 0] > 0)
					{
						if (((HTML_ShowHeadings[1] > 0) & HtmlItem.VersePresent[2]) && HtmlItem.Slide[CurSlide, 0] != 101)
						{
							str = gf.VerseTitle[HtmlItem.Slide[CurSlide, 0]] + NewLine;
						}
						CurFormat = 3;
						flag = true;
					}
					if (flag)
					{
					}
					if (HtmlItem.Slide[CurSlide, 2] > 0)
					{
						str2 = str + AddtoHtmlFile(HtmlItem.Slide[CurSlide, 1], HtmlItem.Slide[CurSlide, 2]);
						stringBuilder.Append(((CurFormat == 4) ? "" : NewLine) + str2 + ((CurFormat == 4) ? "" : ((HtmlItem.Slide[CurSlide, 4] > 0) ? "" : NewLine)));
						str = "";
					}
					if (HtmlItem.Slide[CurSlide, 4] > 0)
					{
						str2 = str + AddtoHtmlFile(HtmlItem.Slide[CurSlide, 3], HtmlItem.Slide[CurSlide, 4]);
						stringBuilder.Append(((CurFormat == 4) ? "" : NewLine) + str2 + ((CurFormat == 4) ? "" : NewLine));
					}
					if (ShowFirstLineOnly)
					{
						i += InChorusSlideCount - 1;
					}
				}
				if (CopyrightInfo != "")
				{
					stringBuilder.Append("</p><font size=\"2\">" + CopyrightInfo);
				}
				str2 = "";
				if ((BookRefInfo != "") & gf.HTMLShowBookRef)
				{
					stringBuilder.Append(((CopyrightInfo == "") ? "</p><font size=\"2\">" : "<BR>") + BookRefInfo);
				}
				str2 = "";
				if ((UserRefInfo != "") & gf.HTMLShowUserRef)
				{
					stringBuilder.Append((((CopyrightInfo == "") & (BookRefInfo == "")) ? "</p><font size=\"2\">" : "<BR>") + UserRefInfo);
				}
				stringBuilder.Append("</p>&nbsp;</div></SPAN>");
				FileUtil.CreateNewFile(gf.GenHTMLDir + OutputFileName + ".htm", (!gf.HTMLDoubleByte) ? FileUtil.FileContentsType.Ascii_Html : FileUtil.FileContentsType.DoubleByte, stringBuilder.ToString());
				stringBuilder.Remove(0, stringBuilder.Length);
			}
			catch
			{
			}
		}

		private string AddtoHtmlFile(int StartLoc, int EndLoc)
		{
			string text = "";
			if (ShowFirstLineOnly)
			{
				text = HtmlItem.LyricsAndNotationsList.Items[StartLoc].SubItems[2].Text + " ..." + NewLine;
			}
			else
			{
				for (int i = StartLoc; i <= EndLoc; i++)
				{
					text = text + HtmlItem.LyricsAndNotationsList.Items[i].SubItems[2].Text + NewLine;
				}
			}
			text = DataUtil.TrimEnd(text);
			if (CurFormat == 4)
			{
				return "<blockquote>" + (gf.HTMLShowChorusItalics ? "<em>" : "") + text + (gf.HTMLShowChorusItalics ? "</em>" : "") + "</blockquote>";
			}
			return text;
		}

		private void GenerateOneRTFFile(int InCount, string OutputFileName, int InChorusSlideCount, Font MainFont, Font MainFontR2, Font NotationsFont, Font NotationsFontR2)
		{
			StringBuilder stringBuilder = new StringBuilder();
			MainHeaderInfo1 = "{\\rtf1\\ansi\\ansicpg1252\\deff0\\deflang1033{\\fonttbl{\\f0\\fnil\\fcharset0 " + MainFont.Name + ";}{\\f1\\fnil\\fcharset0 " + MainFontR2.Name + ";}}\\viewkind1\\uc1\\pard\\f0\\fs" + Convert.ToString(MainFont.Size * 2f) + "\\margr600\\margl1000\\margt900\\margb1000 ";
			
			using StreamWriter streamWriter = new StreamWriter($"{gf.GenHTMLDir}{OutputFileName}.rtf", append: false, FileUtil.Utf8WithBom);
			try
			{
				streamWriter.AutoFlush = true;
				streamWriter.Write(MainHeaderInfo1);
				streamWriter.Write(DataUtil.UnicodeToAscii_RTF("\\b1\\ul " + SongTitle + "\\b0\\ulnone " + gf.RTFNewLine));
				if (SongKey != "" || SongCapo > 0)
				{
					SongKey = ((SongKey != "") ? ("Key: " + SongKey + "  ") : "");
					string text = (SongCapo > 0) ? ("Capo " + SongCapo) : "";
					streamWriter.Write(DataUtil.UnicodeToAscii_RTF(gf.RTFNewLine + "\\b0\\ulnone " + SongKey + text + "\\b0\\ulnone "));
				}
				streamWriter.Write(DataUtil.UnicodeToAscii_RTF(gf.RTFNewLine));
				bool flag = false;
				for (int i = 1; i <= HtmlItem.TotalSlides; i++)
				{
					if (HtmlItem.Slide[CurSlide, 0] == 0)
					{
						flag = true;
						i = HtmlItem.TotalSlides + 1;
					}
					else if (((HTML_ShowHeadings[0] > 0) & HtmlItem.VersePresent[2]) && HtmlItem.Slide[CurSlide, 0] != 101 && gf.VerseTitle[HtmlItem.Slide[CurSlide, 0]] != "")
					{
						flag = true;
						i = HtmlItem.TotalSlides + 1;
					}
				}
				string str;
				for (int i = 1; i <= HtmlItem.TotalSlides; i++)
				{
					int curFormat = CurFormat;
					ShowFirstLineOnly = false;
					CurSlide = i;
					string text2 = "";
					if (HtmlItem.Slide[CurSlide, 0] == 0)
					{
						text2 = "\\par ";
						if (HTML_ShowHeadings[0] > 0 && !ChorusDone)
						{
							text2 += gf.FolderLyricsHeading[SongFolderNo, 0];
							text2 = ((text2 != "") ? text2 : "");
						}
						if (!ChorusDone)
						{
							ChorusDone = true;
						}
						else
						{
							ShowFirstLineOnly = true;
						}
						CurFormat = 4;
					}
					else if (HtmlItem.Slide[CurSlide, 0] > 0)
					{
						if (((HTML_ShowHeadings[1] > 0) & HtmlItem.VersePresent[2]) && HtmlItem.Slide[CurSlide, 0] != 101)
						{
							text2 = gf.VerseTitle[HtmlItem.Slide[CurSlide, 0]];
						}
						CurFormat = 3;
					}
					if (HtmlItem.Slide[CurSlide, 2] > 0)
					{
						str = AddtoFTPFile(HtmlItem.Slide[CurSlide, 1], HtmlItem.Slide[CurSlide, 2], MainFont, NotationsFont, 0, CurFormat == 4 || flag, text2);
						stringBuilder.Append(((CurFormat == 4) ? "" : gf.RTFNewLine) + str);
						text2 = "";
					}
					if (HtmlItem.Slide[CurSlide, 4] > 0)
					{
						str = AddtoFTPFile(HtmlItem.Slide[CurSlide, 3], HtmlItem.Slide[CurSlide, 4], MainFontR2, NotationsFontR2, 1, CurFormat == 4 || flag, text2);
						stringBuilder.Append(((CurFormat == 4) ? "" : gf.RTFNewLine) + str);
					}
					if (ShowFirstLineOnly)
					{
						i += InChorusSlideCount - 1;
					}
				}
				stringBuilder.Append(gf.RTFNewLine + gf.RTFIndent[2]);
				if (CopyrightInfo != "")
				{
					stringBuilder.Append(gf.RTFNewLine + CopyrightInfo);
				}
				str = "";
				if ((BookRefInfo != "") & gf.HTMLShowBookRef)
				{
					stringBuilder.Append(gf.RTFNewLine + BookRefInfo);
				}
				str = "";
				if ((UserRefInfo != "") & gf.HTMLShowUserRef)
				{
					stringBuilder.Append(gf.RTFNewLine + UserRefInfo);
				}
				streamWriter.Write(DataUtil.UnicodeToAscii_RTF(stringBuilder.ToString()));
				streamWriter.Write("}");
				//streamWriter.Flush();
				//streamWriter.Close();
			}
			catch
			{
				//streamWriter.Flush();
				//streamWriter.Close();
				MessageBox.Show("Error generating listing " + OutputFileName + ". Document might be in use.");
			}
		}

		private string AddtoFTPFile(int StartLoc, int EndLoc, Font MainFont, Font NotationsFont, int RegionNum, bool HeadingPresent, string HeadingText)
		{
			string text = "";
			string text2 = "";
			string text3 = "";
			string text4 = "\\f" + RegionNum + "\\fs" + Convert.ToString(MainFont.Size * 2f);
			string str = "\\f" + RegionNum + "\\fs" + Convert.ToString(NotationsFont.Size * 2f);
			string text5 = HeadingPresent ? gf.RTFTab : "";
			NotationsPresent = false;
			if (ShowNotations)
			{
				for (int i = StartLoc; i <= EndLoc; i++)
				{
					if (HtmlItem.LyricsAndNotationsList.Items[i].SubItems[3].Text != "")
					{
						NotationsPresent = true;
						i = EndLoc;
					}
				}
			}
			if (ShowFirstLineOnly)
			{
				text2 = "\\par " + text5 + HtmlItem.LyricsAndNotationsList.Items[StartLoc].SubItems[2].Text + " ...\\par ";
			}
			else
			{
				for (int i = StartLoc; i <= EndLoc; i++)
				{
					text3 = HtmlItem.LyricsAndNotationsList.Items[i].SubItems[2].Text;
					if (NotationsPresent)
					{
						text = HtmlItem.LyricsAndNotationsList.Items[i].SubItems[3].Text;
						gf.SubDivideTextAndNotations(text3, text, MainFont, NotationsFont, ref SubDivideList, RTFMaxTextWidth);
						text = str + SubDivideList.Items[0].SubItems[1].Text + "\\par " + text5;
					}
					string text6 = text2;
					text2 = text6 + text5 + text + text4 + text3 + "\\par ";
				}
				text2 = HeadingText + text2;
			}
			text2 = DataUtil.TrimEnd(text2);
			if (CurFormat == 4)
			{
				return gf.RTFIndent[0] + (gf.HTMLShowChorusItalics ? "\\i " : "") + text2 + (gf.HTMLShowChorusItalics ? "\\i0" : "");
			}
			return (HeadingPresent ? gf.RTFIndent[1] : gf.RTFIndent[2]) + text2;
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing && components != null)
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

        private void InitializeComponent()
        {
            components = new Container();
            ComponentResourceManager resources = new ComponentResourceManager(typeof(FrmGenerateHtml));
            HeadingText0 = new TextBox();
            label1 = new Label();
            label2 = new Label();
            HeadingText1 = new TextBox();
            label3 = new Label();
            HeadingText2 = new TextBox();
            MusicLinkcb = new CheckBox();
            MusicNumberscb = new CheckBox();
            ShowindexFilecb = new CheckBox();
            BookRefcb = new CheckBox();
            UserRefcb = new CheckBox();
            ProgressBar1 = new ProgressBar();
            WarningLabel = new Label();
            ToolTip1 = new ToolTip(components);
            OptOutputHTML = new RadioButton();
            OptOutputRTF = new RadioButton();
            BtnCancel = new Button();
            BtnOK = new Button();
            DoubleBytecb = new CheckBox();
            groupBox1 = new GroupBox();
            RTFFontSize = new NumericUpDown();
            label4 = new Label();
            ChorusItaliccb = new CheckBox();
            groupBox1.SuspendLayout();
            ((ISupportInitialize)RTFFontSize).BeginInit();
            SuspendLayout();
            // 
            // HeadingText0
            // 
            HeadingText0.Location = new Point(16, 51);
            HeadingText0.Margin = new Padding(4, 5, 4, 5);
            HeadingText0.Name = "HeadingText0";
            HeadingText0.Size = new Size(596, 27);
            HeadingText0.TabIndex = 0;
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.Location = new Point(15, 25);
            label1.Margin = new Padding(4, 0, 4, 0);
            label1.Name = "label1";
            label1.Size = new Size(254, 20);
            label1.TabIndex = 1;
            label1.Text = "Main Heading - (eg. XYZ Fellowship):";
            // 
            // label2
            // 
            label2.AutoSize = true;
            label2.Location = new Point(16, 86);
            label2.Margin = new Padding(4, 0, 4, 0);
            label2.Name = "label2";
            label2.Size = new Size(465, 20);
            label2.TabIndex = 3;
            label2.Text = "Web Address Link for Main Heading  (eg. http://www.easislides.com):";
            // 
            // HeadingText1
            // 
            HeadingText1.Location = new Point(17, 109);
            HeadingText1.Margin = new Padding(4, 5, 4, 5);
            HeadingText1.Name = "HeadingText1";
            HeadingText1.Size = new Size(596, 27);
            HeadingText1.TabIndex = 1;
            // 
            // label3
            // 
            label3.AutoSize = true;
            label3.Location = new Point(16, 146);
            label3.Margin = new Padding(4, 0, 4, 0);
            label3.Name = "label3";
            label3.Size = new Size(319, 20);
            label3.TabIndex = 5;
            label3.Text = "Secondary Heading (eg. List of Worship Songs)";
            // 
            // HeadingText2
            // 
            HeadingText2.Location = new Point(17, 171);
            HeadingText2.Margin = new Padding(4, 5, 4, 5);
            HeadingText2.Name = "HeadingText2";
            HeadingText2.Size = new Size(596, 27);
            HeadingText2.TabIndex = 2;
            // 
            // MusicLinkcb
            // 
            MusicLinkcb.AutoSize = true;
            MusicLinkcb.Location = new Point(17, 212);
            MusicLinkcb.Margin = new Padding(4, 5, 4, 5);
            MusicLinkcb.Name = "MusicLinkcb";
            MusicLinkcb.Size = new Size(227, 24);
            MusicLinkcb.TabIndex = 3;
            MusicLinkcb.Text = "Link to Music Files if available";
            // 
            // MusicNumberscb
            // 
            MusicNumberscb.AutoSize = true;
            MusicNumberscb.Location = new Point(17, 265);
            MusicNumberscb.Margin = new Padding(4, 5, 4, 5);
            MusicNumberscb.Name = "MusicNumberscb";
            MusicNumberscb.Size = new Size(184, 24);
            MusicNumberscb.TabIndex = 5;
            MusicNumberscb.Text = "Show Song Numbering";
            // 
            // ShowindexFilecb
            // 
            ShowindexFilecb.AutoSize = true;
            ShowindexFilecb.Location = new Point(17, 291);
            ShowindexFilecb.Margin = new Padding(4, 5, 4, 5);
            ShowindexFilecb.Name = "ShowindexFilecb";
            ShowindexFilecb.Size = new Size(247, 24);
            ShowindexFilecb.TabIndex = 6;
            ShowindexFilecb.Text = "Show index.htm after generation";
            // 
            // BookRefcb
            // 
            BookRefcb.AutoSize = true;
            BookRefcb.Location = new Point(259, 212);
            BookRefcb.Margin = new Padding(4, 5, 4, 5);
            BookRefcb.Name = "BookRefcb";
            BookRefcb.Size = new Size(175, 24);
            BookRefcb.TabIndex = 7;
            BookRefcb.Text = "Show Book Reference";
            // 
            // UserRefcb
            // 
            UserRefcb.AutoSize = true;
            UserRefcb.Location = new Point(259, 238);
            UserRefcb.Margin = new Padding(4, 5, 4, 5);
            UserRefcb.Name = "UserRefcb";
            UserRefcb.Size = new Size(170, 24);
            UserRefcb.TabIndex = 8;
            UserRefcb.Text = "Show User Reference";
            // 
            // ProgressBar1
            // 
            ProgressBar1.Location = new Point(16, 325);
            ProgressBar1.Margin = new Padding(4, 5, 4, 5);
            ProgressBar1.Name = "ProgressBar1";
            ProgressBar1.Size = new Size(596, 32);
            ProgressBar1.Step = 1;
            ProgressBar1.Style = ProgressBarStyle.Continuous;
            ProgressBar1.TabIndex = 11;
            // 
            // WarningLabel
            // 
            WarningLabel.Location = new Point(27, 331);
            WarningLabel.Margin = new Padding(4, 0, 4, 0);
            WarningLabel.Name = "WarningLabel";
            WarningLabel.Size = new Size(573, 20);
            WarningLabel.TabIndex = 12;
            // 
            // OptOutputHTML
            // 
            OptOutputHTML.AutoSize = true;
            OptOutputHTML.Checked = true;
            OptOutputHTML.Location = new Point(8, 18);
            OptOutputHTML.Margin = new Padding(4, 5, 4, 5);
            OptOutputHTML.Name = "OptOutputHTML";
            OptOutputHTML.Size = new Size(102, 24);
            OptOutputHTML.TabIndex = 0;
            OptOutputHTML.TabStop = true;
            OptOutputHTML.Text = "HTML Files";
            ToolTip1.SetToolTip(OptOutputHTML, "HTML style files");
            OptOutputHTML.UseVisualStyleBackColor = true;
            // 
            // OptOutputRTF
            // 
            OptOutputRTF.AutoSize = true;
            OptOutputRTF.Location = new Point(8, 51);
            OptOutputRTF.Margin = new Padding(4, 5, 4, 5);
            OptOutputRTF.Name = "OptOutputRTF";
            OptOutputRTF.Size = new Size(86, 24);
            OptOutputRTF.TabIndex = 1;
            OptOutputRTF.Text = "RTF Files";
            ToolTip1.SetToolTip(OptOutputRTF, "Rich Text Format Files with Notations (if any)");
            OptOutputRTF.UseVisualStyleBackColor = true;
            // 
            // BtnCancel
            // 
            BtnCancel.DialogResult = DialogResult.Cancel;
            BtnCancel.Location = new Point(507, 366);
            BtnCancel.Margin = new Padding(4, 5, 4, 5);
            BtnCancel.Name = "BtnCancel";
            BtnCancel.Size = new Size(107, 37);
            BtnCancel.TabIndex = 14;
            BtnCancel.Text = "Close";
            // 
            // BtnOK
            // 
            BtnOK.Location = new Point(379, 366);
            BtnOK.Margin = new Padding(4, 5, 4, 5);
            BtnOK.Name = "BtnOK";
            BtnOK.Size = new Size(107, 37);
            BtnOK.TabIndex = 13;
            BtnOK.Text = "Generate";
            BtnOK.Click += BtnOK_Click;
            // 
            // DoubleBytecb
            // 
            DoubleBytecb.AutoSize = true;
            DoubleBytecb.Location = new Point(259, 265);
            DoubleBytecb.Margin = new Padding(4, 5, 4, 5);
            DoubleBytecb.Name = "DoubleBytecb";
            DoubleBytecb.Size = new Size(174, 24);
            DoubleBytecb.TabIndex = 9;
            DoubleBytecb.Text = "Use Double Byte Files";
            // 
            // groupBox1
            // 
            groupBox1.Controls.Add(RTFFontSize);
            groupBox1.Controls.Add(OptOutputHTML);
            groupBox1.Controls.Add(label4);
            groupBox1.Controls.Add(OptOutputRTF);
            groupBox1.Location = new Point(455, 202);
            groupBox1.Margin = new Padding(4, 5, 4, 5);
            groupBox1.Name = "groupBox1";
            groupBox1.Padding = new Padding(4, 5, 4, 5);
            groupBox1.Size = new Size(160, 114);
            groupBox1.TabIndex = 10;
            groupBox1.TabStop = false;
            // 
            // RTFFontSize
            // 
            RTFFontSize.Location = new Point(99, 75);
            RTFFontSize.Margin = new Padding(4, 5, 4, 5);
            RTFFontSize.Maximum = new decimal(new int[] { 99, 0, 0, 0 });
            RTFFontSize.Minimum = new decimal(new int[] { 6, 0, 0, 0 });
            RTFFontSize.Name = "RTFFontSize";
            RTFFontSize.Size = new Size(53, 27);
            RTFFontSize.TabIndex = 16;
            RTFFontSize.Value = new decimal(new int[] { 12, 0, 0, 0 });
            // 
            // label4
            // 
            label4.AutoSize = true;
            label4.Location = new Point(28, 82);
            label4.Margin = new Padding(4, 0, 4, 0);
            label4.Name = "label4";
            label4.Size = new Size(72, 20);
            label4.TabIndex = 15;
            label4.Text = "Font Size:";
            // 
            // ChorusItaliccb
            // 
            ChorusItaliccb.AutoSize = true;
            ChorusItaliccb.Location = new Point(17, 238);
            ChorusItaliccb.Margin = new Padding(4, 5, 4, 5);
            ChorusItaliccb.Name = "ChorusItaliccb";
            ChorusItaliccb.Size = new Size(174, 24);
            ChorusItaliccb.TabIndex = 4;
            ChorusItaliccb.Text = "Show Chorus in Italics";
            // 
            // FrmGenerateHtml
            // 
            AcceptButton = BtnOK;
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(629, 429);
            Controls.Add(ChorusItaliccb);
            Controls.Add(DoubleBytecb);
            Controls.Add(BtnCancel);
            Controls.Add(BtnOK);
            Controls.Add(WarningLabel);
            Controls.Add(ProgressBar1);
            Controls.Add(UserRefcb);
            Controls.Add(BookRefcb);
            Controls.Add(HeadingText2);
            Controls.Add(HeadingText1);
            Controls.Add(HeadingText0);
            Controls.Add(ShowindexFilecb);
            Controls.Add(MusicNumberscb);
            Controls.Add(MusicLinkcb);
            Controls.Add(groupBox1);
            Controls.Add(label3);
            Controls.Add(label2);
            Controls.Add(label1);
            FormBorderStyle = FormBorderStyle.FixedDialog;
            Icon = (Icon)resources.GetObject("$this.Icon");
            Margin = new Padding(4, 5, 4, 5);
            MaximizeBox = false;
            MinimizeBox = false;
            Name = "FrmGenerateHtml";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Generate HTML";
            Load += FrmGenerateHTML_Load;
            groupBox1.ResumeLayout(false);
            groupBox1.PerformLayout();
            ((ISupportInitialize)RTFFontSize).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }
    }
}
